<!-- ****************************************
     |docname| - main template for this theme
     **************************************** -->
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="generator" content="Docutils 0.19: https://docutils.sourceforge.io/" />

    <title>3.9. Exception handling &#8212; CISC 187 Course Reader Overview</title>
    <link rel="stylesheet" type="text/css" href="../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../_static/basic.css" />
    <link rel="stylesheet" type="text/css" href="../_static/graphviz.css" />
    <link rel="stylesheet" type="text/css" href="../_static/plot_directive.css" />
    <link rel="stylesheet" type="text/css" href="../_static/accessibility.css?v=50109A2C" />
    <link rel="stylesheet" type="text/css" href="../_static/matrixeq.css?v=58BC228F" />
    <link rel="stylesheet" type="text/css" href="../_static/bootstrap-sphinx.css" />
    <link rel="stylesheet" type="text/css" href="../_static/637.0fa6cababf056764.css?v=F9484CEF" />
    <link rel="stylesheet" type="text/css" href="../_static/runestone.3eb60bc006ae9a54.css?v=3A5A250C" />



    <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/_sphinx_javascript_frameworks_compat.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/sphinx_highlight.js"></script>
    <script src="../_static/animationbase.js?v=A043C3A7"></script>
    <script src="../_static/matrixeq.js?v=D64CFA5A"></script>
    <script src="../_static/runtime.66b619f51b746382.bundle.js?v=C3F69EE5"></script>
    <script src="../_static/637.d54be67956c5c660.bundle.js?v=915B1670"></script>
    <script src="../_static/runestone.ecc6dff5cad8b815.bundle.js?v=AE959292"></script>
    <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script src="https://media.ethicalads.io/media/client/ethicalads.min.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="next" title="3.10. Static functions and variables" href="static-functions.html" />
    <link rel="prev" title="3.8. Error handling" href="error-handling.html" />


<link rel="shortcut icon" href="/cisc187-reader/static/favicon.ico" type="image/ico" />



<link rel="canonical" href="https://{{canonical_host}}{{new_server_prefix}}/books/published/{{base_course}}/{{pagepath}}" />


<script>
  eBookConfig = {};
  
    eBookConfig.useRunestoneServices = false;
    eBookConfig.host = 'https://daveparillo.github.io/cisc187-reader/' || 'http://127.0.0.1:8000';
    eBookConfig.app = eBookConfig.host+'/cisc187-reader';
    eBookConfig.course = 'cisc187-reader';
    eBookConfig.basecourse = 'cisc187-reader';
    eBookConfig.isLoggedIn = false;
    eBookConfig.enableCompareMe = eBookConfig.useRunestoneServices;
    eBookConfig.new_server_prefix = '';
  
  eBookConfig.ajaxURL = eBookConfig.app+'/ajax/';
  eBookConfig.logLevel = 0;
  eBookConfig.loginRequired = false;
  eBookConfig.build_info = "unknown";
  eBookConfig.python3 = true;
  eBookConfig.acDefaultLanguage = 'cpp' ? 'cpp' : 'python'
  eBookConfig.runestone_version = '6.6.2';
  eBookConfig.jobehost = 'https://delicate-frost-8843.fly.dev';
  eBookConfig.proxyuri_runs = '/jobe/index.php/restapi/runs/';
  eBookConfig.proxyuri_files = '/jobe/index.php/restapi/files/';
  eBookConfig.enable_chatcodes = false ? false : false;
  eBookConfig.enableScratchAC = true;

</script>

<!-- Ad Serving Headers Only serve ads to Anonymous Users -->



  </head><body>


<!-- Begin navbar -->
<div id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation">

  <div class="container">

    <div class="navbar-header">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <button type='button' class='navbar-toggle' data-toggle="collapse" data-target=".navbar-ex1-collapse" aria-label="navbar toggle">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div>
        
        
          <div class="brand-logo"><img src="../_static/img/RAIcon.png" alt=""></div>
        
        <a class="navbar-brand" href="../index.html" aria-label="index-page">
          
          cisc187-reader
        </a>
      </div>
    </div>



    <div class="navbar-collapse collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right" >

        <li class="divider-vertical"></li>

        <!-- social media dropdown -->
        <!-- end social media dropdown -->

        <li class="divider-vertical"></li>
        <!-- search dropdown -->
        <li class="dropdown">
          <a class="dropdown-toggle" href="#" data-toggle="dropdown">
            <i class="glyphicon glyphicon-search" style='opacity:0.9;'><span class="visuallyhidden" aria-label="Search">Search</span></i>
          </a>
          <ul class='dropdown-menu'>
            
                <li><a href='../index.html' aria-label="index-page">Table of Contents</a></li>
            
            <li><a href='../genindex.html'>Book Index</a></li>
            <li class="divider"></li>
            <li style="width: 240px;">
              <form class="navbar-search" style="margin:10px;" action="../search.html" method="get">
                <div class="input-group">
                  <input type="text" class="form-control" name="q" placeholder="Search this book" />
                  <span class="input-group-btn">
                    <button class="btn btn-primary" style="margin:0;" type="submit">
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                  </span>
                </div><!-- /input-group -->
                <input type="hidden" name="check_keywords" value="yes" />
                <input type="hidden" name="area" value="default" />
              </form>
            </li>
          </ul>
        </li>
        <!-- end search dropdown -->

        <li class="divider-vertical"></li>

        
        <li class="divider-vertical"></li>
        <!-- <li id="scratch_ac_link"><a href="javascript:ACFactory.toggleScratchActivecode()">Scratch ActiveCode</a></li> -->

        <!-- <li class="dropdown">             -->
          <li id="scratch_ac_link" class="dropdown"><a href="javascript:runestoneComponents.popupScratchAC()">
              <i class="glyphicon glyphicon-pencil" style="opacity:0.9;"><span class="visuallyhidden" aria-label="Scratch Activecode" >Scratch Activecode</span></i></a></li>
        <!-- </li> -->

        <li class="divider-vertical"></li>

        
      </ul>

      <ul class="nav navbar-nav">
        <li class="divider-vertical"></li>
        
          
          <li class="divider-vertical"></li>
        
        <!-- 
          
  <li id="relations-prev" title="Previous Chapter - <span class="section-number">3.8. </span>Error handling" data-toggle="tooltip">
    <a href="error-handling.html" >
      <i class='glyphicon glyphicon-backward' style='opacity:0.9;'></i>
    </a>
  </li>
  
  <li id="relations-next" title='Next Chapter - <span class="section-number">3.10. </span>Static functions and variables' data-toggle="tooltip" >              
    <a href="static-functions.html" >
        <i class='glyphicon glyphicon-forward' style='opacity:0.9;'></i>
    </a>
  </li>
  <li class="divider-vertical"></li>

<script>
  opts = {'placement':'bottom',
          'selector': '',
          'delay': { show: 100, hide: 50}
         };

  window.addEventListener('load', (event) => {
    $('#relations-prev').tooltip(opts);
    $('#relations-next').tooltip(opts);
  });
</script>
        -->
        
          <li></li>
        
      </ul>
      </div> <!-- navbar-collapse -->
    </div> <!-- navbar -->
  </div> <!-- container -->


<div class="container" id="continue-reading"></div>

<div class="container" id="main-content" role="main">

<!-- Ad Serving for Runestone Campaign -->


  
  <section id="exception-handling">
<span id="index-0"></span><h1><span class="section-number">3.9. </span>Exception handling<a class="headerlink" href="#exception-handling" title="Permalink to this heading">¶</a></h1>
<p>An alternative to returning values from functions is to use <strong>exceptions</strong>.</p>
<p>A C++ exception is a response to an exceptional circumstance that occurs while a program is running,
such as an attempt to open a file that does not exist.</p>
<p>Exceptions provide a way to transfer control from one part of a program
(where the error occurs) to another (where the error is ‘handled’).
C++ exception handling is built upon three keywords: <code class="docutils literal notranslate"><span class="pre">try</span></code>, <code class="docutils literal notranslate"><span class="pre">catch</span></code>, and <code class="docutils literal notranslate"><span class="pre">throw</span></code>.</p>
<dl class="simple">
<dt>throw</dt><dd><p>A program <a class="reference external" href="https://en.cppreference.com/w/cpp/language/throw">throws</a> an exception when a problem shows up.</p>
</dd>
<dt>try</dt><dd><p>A <a class="reference external" href="https://en.cppreference.com/w/cpp/language/try_catch">throws</a> block identifies a block of code for which particular exceptions will be activated.
It’s followed by one or more <code class="docutils literal notranslate"><span class="pre">catch</span></code> blocks.</p>
</dd>
<dt>catch</dt><dd><p>A program <a class="reference external" href="https://en.cppreference.com/w/cpp/language/try_catch">catches</a> an exception with an exception handler at the place
in a program where you want to handle the problem.</p>
</dd>
<dt>finally</dt><dd><p>The <strong>finally</strong> block allows the code to clean up after resources regardless
of what exception may have been caught.</p>
</dd>
</dl>
<p>Basic anatomy of an exception</p>
<ol class="arabic simple">
<li><p>Surround potentially error throwing code in a <code class="docutils literal notranslate"><span class="pre">try</span></code> block</p></li>
<li><p>After the <code class="docutils literal notranslate"><span class="pre">try</span></code> block, include 1 or more <code class="docutils literal notranslate"><span class="pre">catch</span></code> blocks</p>
<ol class="loweralpha simple">
<li><p>The parameter in the catch identifies the type of exception the catch block will handle</p></li>
</ol>
</li>
</ol>
<blockquote>
<div><div class="highlight-cpp notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">  </span><span class="c1">// execute potentially dangerous statements</span>
<span class="p">}</span>

<span class="c1">// catch a specific class of exceptions</span>
<span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="k">const</span><span class="w"> </span><span class="n">std</span><span class="o">::</span><span class="n">exception</span><span class="o">&amp;</span><span class="w"> </span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">  </span><span class="n">std</span><span class="o">::</span><span class="n">cout</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="s">&quot;Exception occurred.</span><span class="se">\n</span><span class="s">&quot;</span><span class="p">;</span>
<span class="w">  </span><span class="n">std</span><span class="o">::</span><span class="n">cout</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="s">&quot;Details: &quot;</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="n">e</span><span class="p">.</span><span class="n">what</span><span class="p">()</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span>
<span class="p">}</span>
</pre></div>
</div>
</div></blockquote>
<p>If you specify a <code class="docutils literal notranslate"><span class="pre">try</span></code>, you must include at least 1 <code class="docutils literal notranslate"><span class="pre">catch</span></code>.</p>
<p>Passing catch parameters by <em>const reference</em> is considered a best practice</p>
<ul>
<li><p>std::exception.what()</p>
<ul class="simple">
<li><p>Returns a description of what caused the error</p></li>
</ul>
</li>
<li><p>More than one <code class="docutils literal notranslate"><span class="pre">catch</span></code> block is acceptable</p></li>
<li><p>The special catch</p>
<div class="highlight-cpp notranslate"><div class="highlight"><pre><span></span><span class="k">catch</span><span class="w"> </span><span class="p">(...)</span>
</pre></div>
</div>
</li>
</ul>
<p>will catch any exception.
If you use this, then you should be prepared to really handle <em>anything</em>.</p>
<section id="standard-exceptions">
<span id="index-1"></span><h2><span class="section-number">3.9.1. </span>Standard exceptions<a class="headerlink" href="#standard-exceptions" title="Permalink to this heading">¶</a></h2>
<p>The standard exceptions in C++ are organized in a class hierarchy.</p>
<ul class="simple">
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::exception">std::exception</a> is the base class for all exceptions</p></li>
<li><p>Classes derived from <a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::exception">std::exception</a></p>
<ul>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::bad_alloc">std::bad_alloc</a>: thrown by <code class="docutils literal notranslate"><span class="pre">new</span></code> and other memory allocation errors</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::bad_cast">std::bad_cast</a>: thrown by <code class="docutils literal notranslate"><span class="pre">dynamic_cast</span></code> and similar</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::bad_typeid">std::bad_typeid</a>: thrown by <code class="docutils literal notranslate"><span class="pre">typeid</span></code></p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::bad_exception">std::bad_exception</a>: runtime unexpected or pointer exceptions</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::logic_error">std::logic_error</a>: exceptions that <em>should</em> be detected by reading the code</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::runtime_error">std::runtime_error</a>: exceptions that theoretically can’t be detected by reading the code</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::logic_error">std::logic_error</a>, and <code class="docutils literal notranslate"><span class="pre">std::runtime_error</span></code> are also exception bases</p></li>
</ul>
</li>
<li><p>Classes derived from <a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::logic_error">std::logic_error</a></p>
<ul>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::domain_error">std::domain_error</a>: invalid mathematical domain</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::invalid_argument">std::invalid_argument</a>: bad parameters or arguments used</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::length_error">std::length_error</a>: Thrown when a std::string is too large</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::out_of_range">std::out_of_range</a>: Used for range checked access, vector.at(x)</p></li>
</ul>
</li>
<li><p>Classes derived from <a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::runtime_error">std::runtime_error</a></p>
<ul>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::overflow_error">std::overflow_error</a>: mathematical overflow</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::range_error">std::range_error</a>: Thrown when storing an out of range value</p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/mwiki/index.php?search=std::underflow_error">std::underflow_error</a>: mathematical underflow</p></li>
</ul>
</li>
</ul>
</section>
<section id="using-exceptions">
<h2><span class="section-number">3.9.2. </span>Using exceptions<a class="headerlink" href="#using-exceptions" title="Permalink to this heading">¶</a></h2>
<p>C++ exceptions are designed to support <em>error handling</em>.</p>
<p>Use <code class="docutils literal notranslate"><span class="pre">throw</span></code> only to signal an error.
Use <code class="docutils literal notranslate"><span class="pre">catch</span></code> only to specify error handling actions when
you know you can handle it.
Possibly by translating it to another type and re-throwing an exception of that type.
For example, catching a <code class="docutils literal notranslate"><span class="pre">bad_alloc</span></code> and re-throwing a <code class="docutils literal notranslate"><span class="pre">no_space_for_file_buffers</span></code> exception.</p>
<p><strong>Do not</strong> use <code class="docutils literal notranslate"><span class="pre">throw</span></code> to catch a coding error in usage of a function.
Instead, use assert or other mechanism to either stop the program or log the error.</p>
<p><strong>Do not</strong> use <code class="docutils literal notranslate"><span class="pre">throw</span></code> if you discover an unexpected violation of an invariant of your component.
Instead, use <code class="docutils literal notranslate"><span class="pre">assert</span></code> or other mechanism to terminate the program.
Throwing an exception will not cure memory corruption and may lead to further corruption of important user data.</p>
<p>Use <code class="docutils literal notranslate"><span class="pre">try</span></code> and <code class="docutils literal notranslate"><span class="pre">catch</span></code> blocks
if the logic is more clear than checking a condition and returning a value.
For example,
if you need to propagate errors several levels up the stack:</p>
<div class="highlight-cpp notranslate"><div class="highlight"><pre><span></span><span class="kt">void</span><span class="w"> </span><span class="nf">f1</span><span class="p">()</span><span class="w"> </span><span class="p">{</span>
<span class="w">  </span><span class="k">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">f2</span><span class="p">();</span>
<span class="w">  </span><span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="k">const</span><span class="w"> </span><span class="n">some_exception</span><span class="o">&amp;</span><span class="w"> </span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="c1">// ... handle error</span>
<span class="w">  </span><span class="p">}</span>
<span class="p">}</span>
<span class="kt">void</span><span class="w"> </span><span class="nf">f2</span><span class="p">()</span><span class="w"> </span><span class="p">{</span><span class="w"> </span><span class="p">...;</span><span class="w"> </span><span class="n">f3</span><span class="p">();</span><span class="w"> </span><span class="p">...;</span><span class="w"> </span><span class="p">}</span>
<span class="kt">void</span><span class="w"> </span><span class="nf">f3</span><span class="p">()</span><span class="w"> </span><span class="p">{</span><span class="w"> </span><span class="p">...;</span><span class="w"> </span><span class="n">f4</span><span class="p">();</span><span class="w"> </span><span class="p">...;</span><span class="w"> </span><span class="p">}</span>
<span class="kt">void</span><span class="w"> </span><span class="nf">f4</span><span class="p">()</span><span class="w"> </span><span class="p">{</span><span class="w"> </span><span class="p">...;</span><span class="w"> </span><span class="n">f5</span><span class="p">();</span><span class="w"> </span><span class="p">...;</span><span class="w"> </span><span class="p">}</span>
<span class="kt">void</span><span class="w"> </span><span class="nf">f5</span><span class="p">()</span>
<span class="p">{</span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="w"> </span><span class="cm">/*...some error condition...*/</span><span class="w"> </span><span class="p">)</span>
<span class="w">    </span><span class="k">throw</span><span class="w"> </span><span class="n">some_exception</span><span class="p">();</span>
<span class="p">}</span>
</pre></div>
</div>
<p>Only the code that detects the error, <code class="docutils literal notranslate"><span class="pre">f5()</span></code>,
and the code that handles the error, <code class="docutils literal notranslate"><span class="pre">f1()</span></code>, have any clutter.
None of the other functions have to worry about passing error codes either in return values
or in extra parameters that would have to be mutable.</p>
<p>Do not use <code class="docutils literal notranslate"><span class="pre">try</span></code> blocks to reclaim resources.
This is a Java technique,
which is great for Java, but is not needed in C++.
In C++, use Resource Acquisition Is Initialization (<a class="reference internal" href="../glossary.html#term-RAII"><span class="xref std std-term">RAII</span></a>).</p>
<p>Use constructors to allocate resources
and use destructors to clean up resources,</p>
<p>Do not use <code class="docutils literal notranslate"><span class="pre">try</span></code> blocks as a proxy for error return codes.
This results in too many <code class="docutils literal notranslate"><span class="pre">try</span></code> blocks cluttering up functions,
which harms readability if nothing else.</p>
</section>
<section id="exceptions-and-i-o-streams">
<span id="index-2"></span><h2><span class="section-number">3.9.3. </span>Exceptions and I/O streams<a class="headerlink" href="#exceptions-and-i-o-streams" title="Permalink to this heading">¶</a></h2>
<p>I/O streams can be configured to throw exceptions with <code class="docutils literal notranslate"><span class="pre">std::basic_ios::exceptions</span></code>.
This object gets and sets the exception mask of the stream.
The exception mask set in the program determines which error states
in the stream will throw an exception if an error is encountered.
If no exception bits are set, then the I/O streams in C++ will not throw any exceptions.</p>
<p>For example:</p>
<div class="highlight-cpp notranslate"><div class="highlight"><pre><span></span><span class="n">std</span><span class="o">::</span><span class="n">ifstream</span><span class="w"> </span><span class="n">ifs</span><span class="p">(</span><span class="s">&quot;in.txt&quot;</span><span class="p">);</span>
<span class="n">ifs</span><span class="p">.</span><span class="n">exceptions</span><span class="p">(</span><span class="n">std</span><span class="o">::</span><span class="n">ifstream</span><span class="o">::</span><span class="n">failbit</span><span class="p">);</span>
</pre></div>
</div>
<p>At this point, only the <code class="docutils literal notranslate"><span class="pre">failbit</span></code> will trigger an exception.</p>
<p>I/O Streams may throw <code class="docutils literal notranslate"><span class="pre">ios_base::failure</span></code>
But since C++11 this class inheritance changed.</p>
<p><code class="docutils literal notranslate"><span class="pre">ios_base::failure</span></code> inherits from <code class="docutils literal notranslate"><span class="pre">std::system_error</span></code></p>
<p>The end result is that <code class="docutils literal notranslate"><span class="pre">ios_base::failure</span></code> now has
an <code class="docutils literal notranslate"><span class="pre">error_code</span></code> member to the exception object it didn’t used to have.</p>
<div class="highlight-cpp notranslate"><div class="highlight"><pre><span></span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="k">const</span><span class="w"> </span><span class="n">ios_base</span><span class="o">::</span><span class="n">failure</span><span class="o">&amp;</span><span class="w"> </span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">  </span><span class="n">std</span><span class="o">::</span><span class="n">cout</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="s">&quot;I/O exception occurred.</span><span class="se">\n</span><span class="s">&quot;</span><span class="p">;</span>
<span class="w">  </span><span class="n">std</span><span class="o">::</span><span class="n">cout</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="s">&quot;Details: &quot;</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="n">e</span><span class="p">.</span><span class="n">what</span><span class="p">()</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span>
<span class="w">  </span><span class="n">std</span><span class="o">::</span><span class="n">cout</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="s">&quot;Code: &quot;</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="n">e</span><span class="p">.</span><span class="n">code</span><span class="p">()</span><span class="w"> </span><span class="o">&lt;&lt;</span><span class="w"> </span><span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span>
<span class="p">}</span>
</pre></div>
</div>
<hr class="docutils" />
<div class="admonition-more-to-explore admonition">
<p class="admonition-title">More to Explore</p>
<ul class="simple">
<li><p><a class="reference external" href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-errors">CPP Core Guidelines: Error Handling</a></p></li>
<li><p><a class="reference external" href="https://isocpp.org/wiki/faq/exceptions">ISO C++ FAQ Exceptions</a></p></li>
<li><p><a class="reference external" href="http://www.acodersjourney.com/2016/08/top-15-c-exception-handling-mistakes-avoid/">Top 15 exception handling mistakes to avoid</a></p></li>
<li><p>Overview of the <a class="reference external" href="http://en.cppreference.com/w/cpp/error">error handling</a> library and
<a class="reference external" href="http://en.cppreference.com/w/cpp/language/exceptions">exceptions</a></p></li>
<li><p><a class="reference external" href="http://en.cppreference.com/w/cpp/language/try_catch">try-catch</a> and
<a class="reference external" href="http://en.cppreference.com/w/cpp/language/throw">throw</a></p></li>
<li><p>Post from Eric Lippert on
<a class="reference external" href="https://blogs.msdn.microsoft.com/ericlippert/2008/09/10/vexing-exceptions/">vexing exceptions</a></p></li>
</ul>
</div>
</section>
</section>


  

  <div id="scprogresscontainer">
    You have attempted <span id="scprogresstotal"></span> of <span id="scprogressposs"></span> activities on this page <div id="subchapterprogress" aria-label="Page progress"></div>
  </div>

  <ul role="navigation" class="nextprev-list nextprev-list" aria-label="Change page">
<li id="relations-prev" class="navLink" title='Previous Section - 3.8. Error handling' data-toggle="tooltip">
  <a href="error-handling.html" aria-label="Previous - 3.8. Error handling">
    <i class='prevNav glyphicon glyphicon-chevron-left'  style="top:50%; transform:translateY(-50%)translateX(-50%); left: 50%; color:black;"></i>
  </a>
</li>

  <li id="relations-next" class="navLink" title='Next Section - 3.10. Static functions and variables' data-toggle="tooltip" >
    <a href="static-functions.html" aria-label="Next - 3.10. Static functions and variables">
      <i id="relationsNextIcon" class='nextNav glyphicon glyphicon-chevron-right' style="top:50%; transform:translateY(-50%)translateX(-50%); left: 50%; color:black; "></i>
    </a>
  </li>
</ul>

<script>
window.addEventListener('load', (event) => {
  $('#relations-prev').tooltip({'placement': 'right', 'delay': { show: 100, hide: 50}});
  $('#relations-next').tooltip({'placement': 'left', 'delay': { show: 100, hide: 50}});
});
</script>

</div>
<footer class="footer">
  <div class="container">
    <p class="pull-right">
      
      | <a href="#">Back to top</a>
      
    </p>
    <p>
        &copy; Copyright 2017-2024 Dave Parillo.
      Created using <a href="http://runestoneinteractive.org/">Runestone</a> 6.6.2.
    </p>
  </div>
</footer>




<script>
  window.addEventListener('load', (event) => {
    runestoneComponents.getSwitch();
  });
</script>


  </body>
</html>